name: DIiscord Notification

on:
 
  pull_request:
  issues:
  issue_comment:
  push:



jobs:
  action:
    runs-on: ubuntu-latest
    
    env:
      debug-output: 
      

    steps:
      - uses: actions/checkout@v4

      - name: Create notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.MY_DISCORD_WEBHOOK }}
        uses: ./

        
